hw5/hw5/Models/COA.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace hw5.Models
{
    /// <summary>
    /// Model for the Change of Address database
    /// </summary>
    public class COA
    {
        public int ID { get; set; }

        [Required, StringLength(32)]
        [Display(Name = "ODL/PERMIT/ID")]
        public string PermitID { get; set; }

        [Required, StringLength(128)]
        [Display(Name = "Full Name")]
        public string FullName { get; set; }

        public DateTime DOB { get; set; }

        [Required, StringLength(256)]
        [Display(Name = "New Address")]
        public string NewAddress { get; set; }

        [Required, StringLength(64)]
        public string City { get; set; }

        [Required, StringLength(64)]
        public string State { get; set; }

        [Required, StringLength(10)]
        [Display(Name = "Zip Code")]
        public string ZipCode { get; set; }

        [Required, StringLength(64)]
        public string County { get; set; }

        public DateTime IssueDate { get; set; }

        public override string ToString()
        {
            return $"{base.ToString()}: {FullName} sent a notice on {IssueDate}";
        }
    }
}

hw5/hw5/Controllers/COAsController.cs
using hw5.DAL;
using hw5.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hw5.Controllers
{
    public class COAsController : Controller
    {
        private COAContext db = new COAContext();

        // GET: COAs
        public ActionResult Index()
        {
            return View(db.COAs.ToList());
        }

        /// <summary>
        /// GET: Change of address form
        /// </summary>
        public ActionResult Form()
        {
            return View();
        }

        /// <summary>
        /// POST: If the form was filled out correctly it will add it to the database
        /// and redirect the user to the list. If not it will not redirect and leave
        /// the forms filled out.
        /// </summary>
        /// <param name="coa"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Form([Bind(Include = "ID,PermitID,FullName,DOB,NewAddress,City,State,ZipCode,County")] COA coa)
        {
            if (ModelState.IsValid)
            {
                coa.IssueDate = DateTime.Today;
                db.COAs.Add(coa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(coa);
        }

        /// <summary>
        /// Clean up method
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

hw5/hw5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hw5.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

hw5/hw5/Views/COAs/Form.cshtml
@model hw5.Models.COA

@{
    ViewBag.Title = "Form";
}

<h2><strong>DMV</strong> Change of Address Notice</h2>

<div class="row">
    <div class="col-md-10">
        <center style="margin-bottom: 20px;"><strong>NOTE:</strong> All information is required</center>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
        
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row" style="padding: 0px; margin: 0px;">

                    <!-- PermitID form group -->
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.PermitID, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.PermitID, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PermitID, "", new { @class = "text-danger" })
                        </div>
                    </div>
        
                    <!-- Date of birth form group -->
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-4"})
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
        
                <!-- Name form group -->
                <div class="form-group">
                    @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", @style = "max-width: 100%;"} })
                        @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                    </div>
                </div>
        
                <!--New Address header/speration-->
                <hr />
                <h3><strong>New Address</strong></h3> 
                <div style="font-size:12px;margin-bottom: 20px;">(No Post Office Number or mail forwarding address)</div>

                <div class="row" style="padding: 0px; margin: 0px;">

                    <!-- City form group -->
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <!-- State form group -->
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="row" style="padding: 0px; margin: 0px;">

                    <!-- County form group -->
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.County, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.County, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.County, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <!-- Zipcode form group -->
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <!-- New Address form group -->
                <div class="form-group">
                    @Html.LabelFor(model => model.NewAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NewAddress, new { htmlAttributes = new { @class = "form-control", @style = "max-width: 100%;" } })
                        @Html.ValidationMessageFor(model => model.NewAddress, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-5 col-md-2">
                        <input type="submit" value="Create" class="btn btn-default" style="width:100%;"/>
                    </div>
                </div>
            </div>
        }
    </div>

    <!-- Side warning message about the law -->
    <div class="col-md-2">
        <div style="border: 1px solid #ffd800; border-radius: 1em; padding: 10px;">Oregon Law requires you to notify DMV of any change of address within 30 days.</div>
    </div>
</div>

hw5/hw5/Views/COAs/Index.cshtml
@model IEnumerable<hw5.Models.COA>

@{
    ViewBag.Title = "List";
}

<h2>Change of Address Forms</h2>

<table class="table" style="border: 3px solid black;">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.PermitID)</th>
            <th>@Html.DisplayNameFor(model => model.FullName)</th>
            <th>@Html.DisplayNameFor(model => model.DOB)</th>
            <th>@Html.DisplayNameFor(model => model.NewAddress)</th>
            <th>@Html.DisplayNameFor(model => model.City)</th>
            <th>@Html.DisplayNameFor(model => model.State)</th>
            <th>@Html.DisplayNameFor(model => model.ZipCode)</th>
            <th>@Html.DisplayNameFor(model => model.County)</th>
            <th>@Html.DisplayNameFor(model => model.IssueDate)</th>
        </tr>
    </thead>
    <tbody>
        <!--Lists all the item in the database-->
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.PermitID)</td>
                <td>@Html.DisplayFor(modelItem => item.FullName)</td>
                <td>@Html.DisplayFor(modelItem => item.DOB)</td>
                <td>@Html.DisplayFor(modelItem => item.NewAddress)</td>
                <td>@Html.DisplayFor(modelItem => item.City)</td>
                <td>@Html.DisplayFor(modelItem => item.State)</td>
                <td>@Html.DisplayFor(modelItem => item.ZipCode)</td>
                <td>@Html.DisplayFor(modelItem => item.County)</td>
                <td>@Html.DisplayFor(modelItem => item.IssueDate)</td>
            </tr>
        }
    </tbody>
</table>

<!--Link to the form-->
<div style="text-align: right;">@Html.ActionLink("Fill out new form", "Form", "COAs")</div>

hw5/hw5/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<ul style="font-size: 22pt;">
    <li>@Html.ActionLink("Change of Address Form", "Form", "COAs")</li>
    <li>@Html.ActionLink("View all forms", "Index", "COAs")</li>
</ul>

hw5/hw5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #293352;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DMV COA Database", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Form", "Form", "COAs")</li>
                    <li>@Html.ActionLink("List", "Index", "COAs")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>